# Site settings
title: Bible Journal & Theological Reflections
description: >-
  A collection of Bible study notes, theological reflections, and spiritual insights
  representing an ongoing journey of understanding Scripture and exploring faith.

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Permalink structure
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
